export const langDate = {
  lang: {
    locale: "es_ES",
    placeholder: "Seleccionar fecha",
    rangePlaceholder: ["Fecha de inicio", "Fecha de fin"],
    today: "Hoy",
    now: "Ahora",
    backToToday: "Volver a hoy",
    ok: "Aceptar",
    clear: "Limpiar",
    month: "Mes",
    year: "año",
    timeSelect: "Seleccionar hora",
    dateSelect: "Seleccionar fecha",
    monthSelect: "Seleccionar mes",
    yearSelect: "Seleccionar año",
    decadeSelect: "Seleccionar década",
    yearFormat: "YYYY",
    dateFormat: "D/M/YYYY",
    dayFormat: "D",
    dateTimeFormat: "D/M/YYYY HH:mm:ss",
    monthBeforeYear: true,
    previousMonth: "Mes anterior (PageUp)",
    nextMonth: "Mes siguiente (PageDown)",
    previousYear: "Año anterior (Control + izquierda)",
    nextYear: "Año siguiente (Control + derecha)",
    previousDecade: "Década anterior",
    nextDecade: "Década siguiente",
    previousCentury: "Siglo anterior",
    nextCentury: "Siglo siguiente",
    shortWeekDays: ["Dom", "Lun", "Mar", "Mié", "Jue", "Vie", "Sáb"],
    shortMonths: [
      "Ene",
      "Feb",
      "Mar",
      "Abr",
      "May",
      "Jun",
      "Jul",
      "Ago",
      "Sep",
      "Oct",
      "Nov",
      "Dic",
    ],
  },
  timePickerLocale: {
    placeholder: "Seleccionar hora",
  },
  dateFormat: "YYYY-MM-DD",
  dateTimeFormat: "YYYY-MM-DD HH:mm:ss",
  weekFormat: "YYYY-wo",
  monthFormat: "YYYY-MM",
};
